#!/usr/bin/env bash
#configures a new ubuntu machine by installing
#nginx where it should listening on port 80
#serve page that would return hello world

echo -e "updating and installing Nginx.\n"
sudo apt-get update -y -qq &&\
	sudo apt-get install nginx -y

echo -e "\nseting up some minor stuff.\n"

#starting nginx service
sudo service nginx start

#allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

#give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

#backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

#create new nginx
echo -e "Hello world!" | dd status=none of=/var/www/html/index.nginx-debian.html

#restartig nginx

sudo service nginx restart

echo -e "\nCompleted.\n"
