#!/usr/bin/env bash
#configures Nginx server so that /redirect_me is redirecting to another page
#the redirection must be "301 moved permanently"

sudo apt-get -y install nginx
sudo bash -c 'echo"Hello world!" > /var/www/html/index.nginx-debian.html'

redirect="\ntlocation /redirect_me {\n\t\treturn 301 http://www.youtube.com/watch?v=QH2-TGU1wu4;\n\t}\n"

# Redirect
sudo sed -i "53|.*|$redirect|" /etc/nginx/sites-enabled/default

# Restart Nginx to apply the changes
sudo /etc/init.d/nginx restart
