#!/usr/bin/env bash
# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create a configuration file for the redirection
sudo bash -c 'cat > /etc/nginx/sites-available/redirect_me.conf << EOF
server {
    listen 80;
    server_name _;
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4\$request_uri;
}
EOF'

# Enable the configuration by creating a symbolic link
sudo ln -s /etc/nginx/sites-available/redirect_me.conf /etc/nginx/sites-enabled/

# Remove the default Nginx configuration
sudo rm /etc/nginx/sites-enabled/default

# Restart Nginx to apply the changes
sudo service nginx restart
